// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
int _Resolution;
RWTexture2D<float4> _Source;

RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint x = id.x;
    uint y = _Resolution - id.y - 1;
    
    Result[id.xy] = _Source[uint2(x, y)];
}
